name: admin_app
description: "Admin portal for food delivery company - manage orders, sellers, and commissions."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Firebase
  firebase_core: ^2.28.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0

  # UI
  fluttertoast: ^8.2.6
  intl: ^0.19.0
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the Flutter
  # team is curated to encourage good coding practices and to maximize the
  # benefits of statically analyzing Flutter code. More information can be found at
  # https://pub.dev/packages/flutter_lints.
  flutter_lints: ^3.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_dash.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to-user-experience/assets/

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to-user-experience/assets/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "fonts:" section. Each entry in this list should have a
  # "family" key with the font family name, and a "family" key set. A
  # "font" key with a font path should be provided for the `weight` in
  # "fonts:" section. A
  # "family" key set. The "fonts:" section allows you to define custom
  # fonts to use in your application.
  # For example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: assets/fonts/Schyler-Regular.ttf
  #       - asset: assets/fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: assets/fonts/TrajanPro.ttf
  #       - asset: assets/fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to-user-experience/assets/#from-packages
